FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY Beauty4u.Jobs ./Beauty4u.Jobs
WORKDIR /src/Beauty4u.Jobs
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Beauty4u.Jobs.dll"]
