version: "3.9"

services:
  beauty4u_api:
    image: beauty4u_api:latest
    container_name: ${API_CONTAINER_NAME}
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    environment:
      DOTNET_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:${API_PORT}"
    volumes:
      - dpkeys:/root/.aspnet/DataProtection-Keys
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${API_PORT}/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

  beauty4u_jobs:
    image: beauty4u_jobs:latest
    container_name: ${JOBS_CONTAINER_NAME}
    ports:
      - "${JOBS_PORT}:${JOBS_PORT}"
    env_file:
      - .env
    environment:
      DOTNET_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:${JOBS_PORT}"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${JOBS_PORT}/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

  beauty4u_web:
    image: beauty4u_web:latest
    container_name: ${WEB_CONTAINER_NAME}
    ports:
      - "${WEB_PORT}:80"
    env_file:
      - .env
    restart: always
    depends_on:
      beauty4u_api:
        condition: service_healthy

volumes:
  dpkeys:
