FROM node:20 AS build
WORKDIR /src
COPY Beauty4u.Web .
RUN npm ci && npm run build -- --output-path=dist

FROM nginx:alpine
COPY --from=build /src/dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
