version: "3.9"

services:
  beauty4u_api:
    image: beauty4u_api:latest
    container_name: ${API_CONTAINER_NAME}
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    environment:
      - DOTNET_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:${API_PORT}
      - ConnectionStrings__B4UConnection=${B4UCONNECTION}
	  - DbConnectionAccess__User=${DBUSER}
	  - DbConnectionAccess__Password=${DBPASSWORD}
	  - Jwt__Key=${JWT_KEY}
	  - Jwt__Issuer=${JWT_ISSUER}
	  - Jwt__Audience=${JWT_AUDIENCE}
	  - Jwt__Secret=${JWT_SECRET}
	  - Jwt__AccessTokenExpiryMinutes=${JWT_ACCESSTOKENEXPIRYMINUTES}
	  - Jwt__RefreshTokenExpiryDays=${JWT_REFRESHTOKENEXPIRYDAYS}
	  - Cors__AllowedOrigins=${CORS_ALLOWEDORIGINS}
	  - HqSettings__IsHq=${ISHQ}
	  - HqSettings__HqApi=${HQAPI}
	  - SchedulerApi=${SCHEDULERAPI}
      - Cors__AllowedOrigins=${CORS_ALLOWED_ORIGINS}
      - HqSettings__IsHq=${HQ_ISHQ}
	  
  beauty4u_jobs:
    image: beauty4u_jobs:latest
    container_name: ${JOBS_CONTAINER_NAME}
    ports:
      - "${JOBS_PORT}:${JOBS_PORT}"
    env_file:
      - .env
    environment:
      - DOTNET_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:${JOBS_PORT}
      - ConnectionStrings__B4UConnection=${B4UCONNECTION}
	  - DbConnectionAccess__User=${DBUSER}
	  - DbConnectionAccess__Password=${DBPASSWORD}
	  - Jwt__Key=${JWT_KEY}
	  - Jwt__Issuer=${JWT_ISSUER}
	  - Jwt__Audience=${JWT_AUDIENCE}
	  - Jwt__Secret=${JWT_SECRET}
	  - Jwt__AccessTokenExpiryMinutes=${JWT_ACCESSTOKENEXPIRYMINUTES}
	  - Jwt__RefreshTokenExpiryDays=${JWT_REFRESHTOKENEXPIRYDAYS}
	  - Cors__AllowedOrigins=${CORS_ALLOWEDORIGINS}
	  - HqSettings__IsHq=${ISHQ}
	  - HqSettings__HqApi=${HQAPI}
	  - SchedulerApi=${SCHEDULERAPI}
      - Cors__AllowedOrigins=${CORS_ALLOWED_ORIGINS}
      - HqSettings__IsHq=${HQ_ISHQ}

  beauty4u_web:
    image: beauty4u_web:latest
    container_name: ${WEB_CONTAINER_NAME}
    ports:
      - "${WEB_PORT}:80"
    env_file:
      - .env
