version: '3.9'
services:
  api:
    image: beauty4u/${BEAUTY4U_API}:latest
    container_name: ${BEAUTY4U_API}
    environment:
      - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT}
	  - ConnectionStrings__B4uConnection=${B4UCONNECTION}
	  - DbConnectionAccess__User=${DBUSER}
	  - DbConnectionAccess__Password=${DBPASSWORD}
	  - Jwt__Key=${JWT_KEY}
	  - Jwt__Issuer=${JWT_ISSUER}
	  - Jwt__Audience=${JWT_AUDIENCE}
	  - Jwt__Secret=${JWT_SECRET}
	  - Jwt__AccessTokenExpiryMinutes=${JWT_ACCESSTOKENEXPIRYMINUTES}
	  - Jwt__RefreshTokenExpiryDays=${JWT_REFRESHTOKENEXPIRYDAYS}
	  - Cors__AllowedOrigins=${CORS_ALLOWEDORIGINS}
	  - HqSettings__IsHq=${ISHQ}
	  - HqSettings__HqApi=${HQAPI}
	  - SchedulerApi=${SCHEDULERAPI}
      - ConnectionStrings__B4uConnection=Server=${DB_SERVER};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASS};TrustServerCertificate=True
      - Cors__AllowedOrigins=${CORS_ALLOWED_ORIGINS}
    ports:
      - "${BEAUTY4U_API_PORT}:5100"
    volumes:
      - /home/${DEPLOY_USER}/${BEAUTY4U_API}:/app/data
    restart: always

  jobs:
    image: beauty4u/${BEAUTY4U_JOBS}:latest
    container_name: ${BEAUTY4U_JOBS}
    environment:
      - DOTNET_ENVIRONMENT=${DOTNET_ENVIRONMENT}
	  - ConnectionStrings__B4uConnection=${B4UCONNECTION}
	  - DbConnectionAccess__User=${DBUSER}
	  - DbConnectionAccess__Password=${DBPASSWORD}
	  - Jwt__Key=${JWT_KEY}
	  - Jwt__Issuer=${JWT_ISSUER}
	  - Jwt__Audience=${JWT_AUDIENCE}
	  - Jwt__Secret=${JWT_SECRET}
	  - Jwt__AccessTokenExpiryMinutes=${JWT_ACCESSTOKENEXPIRYMINUTES}
	  - Jwt__RefreshTokenExpiryDays=${JWT_REFRESHTOKENEXPIRYDAYS}
	  - Cors__AllowedOrigins=${CORS_ALLOWEDORIGINS}
	  - HqSettings__IsHq=${ISHQ}
	  - HqSettings__HqApi=${HQAPI}
	  - SchedulerApi=${SCHEDULERAPI}
      - ConnectionStrings__B4uConnection=Server=${DB_SERVER};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASS};TrustServerCertificate=True
      - Cors__AllowedOrigins=${CORS_ALLOWED_ORIGINS}
    ports:
      - "${BEAUTY4U_JOBS_PORT}:6100"
    volumes:
      - /home/${DEPLOY_USER}/${BEAUTY4U_JOBS}:/app/data
    restart: always

  web:
    image: beauty4u/${BEAUTY4U_UI}:latest
    container_name: ${BEAUTY4U_UI}
    ports:
      - "${BEAUTY4U_UI_PORT}:80"
    volumes:
      - /home/${DEPLOY_USER}/${BEAUTY4U_UI}:/usr/share/nginx/html
    restart: always
