name: Cleanup Containers

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy & Load Docker images to Windows VM
        run: |
          sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }}:"${{ vars.DEPLOY_FOLDER }}"
      
          for contner in beauty4u_web; do
            echo "📦 Removing $contner ..."
            sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" \
              ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} \
              "docker stop" < $contner
          done
      
          sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" \
