name: Cleanup Container

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "preprod_hq"
        type: choice
        options:
          - preprod_hq

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Cleanup old beauty4u containers
        run: |
          sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} powershell -NoProfile -Command '
              `$targets = "beauty4u_hq","beauty4u_th","beauty4u_oh","beauty4u_jobs","beauty4u_web";
              Write-Host "📦 Stopping and removing containers...";
              foreach (`$t in `$targets) {
                `$matches = docker ps -a --format "{{.Names}}" | Where-Object { $_ -like "*`$t*" }
                foreach (`$m in `$matches) {
                  docker stop `$m;
                  docker rm `$m;
                  Write-Host "Stopped and removed container: `$m";
                }
              }
            '

