name: Cleanup Containers

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy & Cleanup Docker containers on Windows VM
        run: |
          # Copy docker-compose.yml to VM
          sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" scp -o StrictHostKeyChecking=no \
            docker-compose.yml \
            ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }}:"${{ vars.DEPLOY_FOLDER }}"
      
          # Stop & remove beauty4u_web container instead of loading images
          echo "🛑 Stopping and removing beauty4u_web ..."
          sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" \
            ssh -o StrictHostKeyChecking=no \
            ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} \
            "docker stop beauty4u_web || true && docker rm beauty4u_web || true"

