name: Cleanup Containers

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml and cleanup containers
        run: |
          # Copy docker-compose.yml to remote VM
          sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" \
            scp -o StrictHostKeyChecking=no docker-compose.yml \
            ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }}:/home/${{ secrets.AZURE_VM_USER }}/docker-compose.yml
          
          # Stop & remove containers
          for container in beauty4u_web; do
            echo "📦 Removing $container ..."
            sshpass -p "${{ secrets.AZURE_VM_PASSWORD }}" \
              ssh -o StrictHostKeyChecking=no \
              ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} \
              "docker stop $container || true && docker rm $container || true"
          done
