name: Deploy Beauty4U

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: "preprod_hq"
        type: choice
        options:
          - preprod_hq

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Build API ---
      - name: Build API
        run: |
          docker build -f Beauty4u.WebApi/Dockerfile -t beauty4u_api:latest Beauty4u.WebApi
          IMAGE_SIZE=$(docker image inspect beauty4u_api:latest --format='{{.Size}}')
          echo "API image size: $IMAGE_SIZE"
          if [ "$IMAGE_SIZE" -eq 0 ]; then
            echo "❌ beauty4u_api:latest image is empty!"
            exit 1
          fi

      # --- Build Jobs ---
      - name: Build Jobs
        run: |
          docker build -f Beauty4u.Jobs/Dockerfile -t beauty4u_jobs:latest Beauty4u.Jobs
          IMAGE_SIZE=$(docker image inspect beauty4u_jobs:latest --format='{{.Size}}')
          echo "Jobs image size: $IMAGE_SIZE"
          if [ "$IMAGE_SIZE" -eq 0 ]; then
            echo "❌ beauty4u_jobs:latest image is empty!"
            exit 1
          fi

      # --- Inject API Base URL for Angular ---
      - name: Inject API Base URL
        run: |
          sed -i "s|API_BASE_URL_PLACEHOLDER|${{ vars.APIBASEURL }}|g" Beauty4u.Web/src/environments/environment.prod.ts

      # --- Build Angular Web ---
      - name: Build Angular Web
        run: |
          docker build -f Beauty4u.Web/Dockerfile -t beauty4u_web:latest Beauty4u.Web
          IMAGE_SIZE=$(docker image inspect beauty4u_web:latest --format='{{.Size}}')
          echo "Web image size: $IMAGE_SIZE"
          if [ "$IMAGE_SIZE" -eq 0 ]; then
            echo "❌ beauty4u_web:latest image is empty!"
            exit 1
          fi

      # --- Save Docker Images as tar ---
      - name: Save Docker Images
        run: |
          docker save beauty4u_api:latest -o beauty4u_api.tar
          docker save beauty4u_jobs:latest -o beauty4u_jobs.tar
          docker save beauty4u_web:latest -o beauty4u_web.tar

      - name: Verify tar files
        run: ls -lh *.tar

      # --- Copy files to Azure VM ---
      - name: Copy to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          source: "beauty4u_api.tar beauty4u_jobs.tar beauty4u_web.tar docker-compose.yml"
          target: "${{ vars.DEPLOY_BASE_FOLDER }}"
          debug: true

      # --- Deploy on Azure VM ---
      - name: Deploy on Azure VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          script: |
            cd ${{ vars.DEPLOY_BASE_FOLDER }}

            # Load Docker images
            docker load -i beauty4u_api.tar
            docker load -i beauty4u_jobs.tar
            docker load -i beauty4u_web.tar

            # Generate .env file safely
            cat <<EOF > .env
B4UCONNECTION='${{ secrets.B4UCONNECTION }}'
API_PORT='${{ vars.BEAUTY4U_API_PORT }}'
API_CONTAINER_NAME='${{ vars.BEAUTY4U_API }}'
JOBS_PORT='${{ vars.BEAUTY4U_JOBS_PORT }}'
JOBS_CONTAINER_NAME='${{ vars.BEAUTY4U_JOBS }}'
WEB_PORT='${{ vars.BEAUTY4U_UI_PORT }}'
WEB_CONTAINER_NAME='${{ vars.BEAUTY4U_UI }}'
DBUSER='${{ secrets.DBUSER }}'
DBPASSWORD='${{ secrets.DBPASSWORD }}'
JWT_AUDIENCE='${{ secrets.JWT_AUDIENCE }}'
JWT_ISSUER='${{ secrets.JWT_ISSUER }}'
JWT_KEY='${{ secrets.JWT_KEY }}'
JWT_SECRET='${{ secrets.JWT_SECRET }}'
JWT_ACCESSTOKENEXPIRYMINUTES='${{ vars.JWT_ACCESSTOKENEXPIRYMINUTES }}'
JWT_REFRESHTOKENEXPIRYDAYS='${{ vars.JWT_REFRESHTOKENEXPIRYDAYS }}'
SCHEDULERAPI='${{ vars.SCHEDULERAPI }}'
HQAPI='${{ vars.HQAPI }}'
ISHQ='${{ vars.HQ_ISHQ }}'
CORS_ALLOWED_ORIGINS='${{ vars.CORS_ALLOWED_ORIGINS }}'
EOF

            # Start containers
            docker compose up -d
